const mongoose = require('mongoose');
const Product = require('./models/Product');
require('dotenv').config();

const products = [
  // ─── PHONES ───────────────────────────────────────────────
  {
    name: 'iPhone 17 Pro Max',
    brand: 'Apple', slug: 'apple-iphone-17-pro-max', category: 'phone',
    image: 'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-17-pro-max-1.jpg',
    storage: ['256GB', '512GB', '1TB'], ram: '8GB',
    display: '6.9 inch Super Retina XDR OLED ProMotion',
    camera: '48MP Main + 48MP Ultra Wide + 48MP Telephoto',
    battery: '5200 mAh', os: 'iOS', featured: true,
    scores: { camera: 10, battery: 8, performance: 10, display: 10, value: 6, build: 10, portability: 7 },
    tags: ['photography', 'premium', 'business', 'ios'],
    prices: [
      { platform: 'amazon', price: 159999, affiliateUrl: 'https://www.amazon.in/iPhone-Pro-Max-256-Promotion/dp/B0FQFNQ5LX/ref=sr_1_1_sspa?sr=8-1-spons&aref=XVOmLfK8nn&sp_csd=d2lkZ2V0TmFtZT1zcF9hdG',inStock: true },
      { platform: 'flipkart', price: 161999, affiliateUrl: 'https://www.flipkart.com/apple-iphone-17-pro-max-silver-256-gb/p/itmd38e30731883a', inStock: true },
    ],
  },
  {
    name: 'iPhone 17',
    brand: 'Apple', slug: 'apple-iphone-17', category: 'phone',
    image: 'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-17-1.jpg',
    storage: ['128GB', '256GB', '512GB'], ram: '8GB',
    display: '6.1 inch Super Retina XDR OLED',
    camera: '48MP Main + 12MP Ultra Wide',
    battery: '3577 mAh', os: 'iOS', featured: true,
    scores: { camera: 9, battery: 7, performance: 9, display: 9, value: 7, build: 9, portability: 9 },
    tags: ['photography', 'premium', 'ios', 'compact'],
    prices: [
      { platform: 'amazon', price: 89999, affiliateUrl: 'https://www.amazon.in/iPhone-17e-256-GB-Starting/dp/B0GQVQY8B7/ref=sr_1_5?sr=8-5', inStock: true },
      { platform: 'flipkart', price: 91999, affiliateUrl: 'https://www.flipkart.com/apple-iphone-17-sage-256-gb/p/itmcfa57eff7729c?pid=MOBHFN6YNAG4ZTHS&lid=LSTMOBHFN6YNAG4ZTHSWUQQUI&marketplace=FLIPKART&q=iphone+17+&store=tyy%2F4io&srno=s_1_1&otracker=search&otracker1=search&fm=organic&iid=0e811c73-0882-44ec-98fe-f50742f2a86c.MOBHFN6YNAG4ZTHS.SEARCH&ppt=None&ppn=None&ssid=v614492ngw0000001774522992735&qH=714a282fe4008576&ov_redirect=true', inStock: true },
    ],
  },
  {
    name: 'Samsung Galaxy S25 Ultra',
    brand: 'Samsung', slug: 'samsung-galaxy-s25-ultra', category: 'phone',
    image: 'https://m.media-amazon.com/images/I/41WyX+E04cL._SY300_SX300_QL70_FMwebp_.jpg',
    storage: ['256GB', '512GB', '1TB'], ram: '12GB',
    display: '6.9 inch Dynamic AMOLED 2X 120Hz',
    camera: '200MP Main + 50MP Ultra Wide + 50MP Telephoto',
    battery: '5000 mAh', os: 'Android', featured: true,
    scores: { camera: 10, battery: 9, performance: 10, display: 10, value: 6, build: 9, portability: 6 },
    tags: ['photography', 'premium', 'android', 'business', 'gaming'],
    prices: [
      { platform: 'amazon', price: 134999, affiliateUrl: 'https://www.amazon.in/Samsung-Smartphone-Titanium-Snapdragon-ProVisual/dp/B0DSKMKJV5/ref=sr_1_3?sr=8-3', inStock: true },
      { platform: 'flipkart', price: 132999, affiliateUrl: 'https://www.flipkart.com/samsung-galaxy-s25-ultra-5g-titanium-whitesilver-256-gb/p/itm9beb2f2beaa5e?pid=MOBH8K8U56WRFZFR&lid=LSTMOBH8K8U56WRFZFRNVXGVH&marketplace=FLIPKART&q=samsung+s25+pro&store=tyy%2F4io&srno=s_1_2&otracker=search&otracker1=search&fm=Search&iid=3aecb356-48b8-4755-8232-2217aae6880f.MOBH8K8U56WRFZFR.SEARCH&ppt=sp&ppn=sp&ssid=ca9xfmbm400000001774523098042&qH=a7455abe06a0a28f&ov_redirect=true', inStock: true },
    ],
  },
  {
    name: 'Samsung Galaxy S25',
    brand: 'Samsung', slug: 'samsung-galaxy-s25', category: 'phone',
    image: 'https://m.media-amazon.com/images/I/41p8ZRc8apL._SY300_SX300_QL70_FMwebp_.jpg',
    storage: ['128GB', '256GB'], ram: '12GB',
    display: '6.2 inch Dynamic AMOLED 2X 120Hz',
    camera: '50MP Main + 12MP Ultra Wide + 10MP Telephoto',
    battery: '4000 mAh', os: 'Android', featured: true,
    scores: { camera: 8, battery: 7, performance: 9, display: 9, value: 7, build: 8, portability: 8 },
    tags: ['android', 'premium', 'compact', 'business'],
    prices: [
      { platform: 'amazon', price: 74999, affiliateUrl: 'https://www.amazon.in/Samsung-Smartphone-Icyblue-Snapdragon-ProVisual/dp/B0DSBVGKVF/ref=sr_1_4?sr=8-4', inStock: true },
      { platform: 'flipkart', price: 72999, affiliateUrl: 'https://www.flipkart.com/samsung-galaxy-s25-5g-silver-shadow-256-gb/p/itm70d1f331ebbac?pid=MOBH8K8UH9XHPVGQ&lid=LSTMOBH8K8UH9XHPVGQEUE4JY&marketplace=FLIPKART&q=samsung+s25+&store=tyy%2F4io&srno=s_1_1&otracker=search&otracker1=search&fm=organic&iid=66579bb5-476c-4089-9817-db12a1063bbe.MOBH8K8UH9XHPVGQ.SEARCH&ppt=None&ppn=None&ssid=imu1hsqqvk0000001774523128050&qH=5666188c16c3e6be&ov_redirect=true', inStock: true },
    ],
  },
  {
    name: 'OnePlus 13',
    brand: 'OnePlus', slug: 'oneplus-13', category: 'phone',
    image: 'https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-13-1.jpg',
    storage: ['256GB', '512GB'], ram: '12GB',
    display: '6.82 inch LTPO AMOLED 120Hz',
    camera: '50MP Hasselblad Main + 50MP Ultra Wide + 50MP Periscope',
    battery: '6000 mAh', os: 'Android', featured: true,
    scores: { camera: 8, battery: 10, performance: 9, display: 9, value: 9, build: 8, portability: 7 },
    tags: ['battery', 'android', 'gaming', 'value', 'performance'],
    prices: [
      { platform: 'amazon', price: 69999, affiliateUrl:'https://www.amazon.in/OnePlus-Smarter-Lifetime-Display-Warranty/dp/B0DQ8W9CTT/ref=sr_1_2?sr=8-2', inStock: true },
      { platform: 'flipkart', price: 68999, affiliateUrl:'https://www.flipkart.com/oneplus-13-midnight-ocean-256-gb/p/itmb4659fd2a037f?pid=MOBH8CHTJ7RGBHAF&lid=LSTMOBH8CHTJ7RGBHAFCY5NHP&marketplace=FLIPKART&q=oneplus+13&store=tyy%2F4io&srno=s_1_1&otracker=search&otracker1=search&fm=Search&iid=4d30f012-a3a4-4459-8956-302e175c7108.MOBH8CHTJ7RGBHAF.SEARCH&ppt=sp&ppn=sp&ssid=bd824hzr5s0000001774523229597&qH=76c7ec185ffef358&ov_redirect=true', inStock: true },
    ],
  },
  {
    name: 'OnePlus 15R',
    brand: 'OnePlus', slug: 'oneplus-15r', category: 'phone',
    image: 'https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-15r-1.jpg',
    storage: ['128GB', '256GB'], ram: '8GB',
    display: '6.77 inch AMOLED 120Hz',
    camera: '50MP Main + 8MP Ultra Wide',
    battery: '6000 mAh', os: 'Android', featured: false,
    scores: { camera: 7, battery: 10, performance: 7, display: 8, value: 10, build: 7, portability: 8 },
    tags: ['battery', 'value', 'budget', 'android', 'student'],
    prices: [
      { platform: 'amazon', price: 39999, affiliateUrl: 'https://www.amazon.in/stores/page/8E6BF28E-AE0B-4A90-93A5-1C7D07B8E896/?_encoding=UTF8&store_ref=SB_A08490631LEW6WSNIWTHE-A0268544PX8Z5LX293SF&pd_rd_plhdr=t&aaxitk=06701eb32cd1ba774ab3fff3826f03e2&hsa_cr_id=0&lp_asins=B0FZT1LXPZ%2CB0FZSXYV6K%2CB0FZT1D63F&lp_query=oneplus%2015R&lp_slot=auto-sparkle-hsa-tetris&aref=Cbm7rW3ZDT&ref_=sbx_s_sparkle_sbtcd_hlhttps://www.amazon.in/dp/oneplus-15r', inStock: true },
      { platform: 'flipkart', price: 38999, affiliateUrl: 'https://www.flipkart.com/oneplus-15r-5g-mint-breeze-256-gb/p/itmc1c624041ba6c?pid=MOBHGUTYS9R3NQRT&lid=LSTMOBHGUTYS9R3NQRTDLSEHL&marketplace=FLIPKART&q=oneplus+15R&store=tyy%2F4io&srno=s_1_1&otracker=search&otracker1=search&fm=organic&iid=2348f88c-b7f2-4959-81be-6d447a21e20f.MOBHGUTYS9R3NQRT.SEARCH&ppt=None&ppn=None&ssid=5x5qcj8mls0000001774523255844&qH=9945c409c66a7f5d&ov_redirect=true', inStock: true },
    ],
  },
  {
    name: 'Nothing Phone 3a',
    brand: 'Nothing', slug: 'nothing-phone-3a', category: 'phone',
    image: 'https://m.media-amazon.com/images/I/41bPQMcRflL._SY300_SX300_QL70_FMwebp_.jpg',
    storage: ['128GB', '256GB'], ram: '8GB',
    display: '6.77 inch AMOLED 120Hz',
    camera: '50MP Main + 50MP Telephoto + 8MP Ultra Wide',
    battery: '5000 mAh', os: 'Android', featured: false,
    scores: { camera: 8, battery: 8, performance: 7, display: 8, value: 10, build: 8, portability: 8 },
    tags: ['value', 'budget', 'student', 'android', 'photography'],
    prices: [
      { platform: 'amazon', price: 27999, affiliateUrl:'https://www.amazon.in/Nothing-Phone-128GB-Storage-White/dp/B0DZTMFWDB/ref=sr_1_4?sr=8-4', inStock: true },
      { platform: 'flipkart', price: 28999, affiliateUrl: 'https://www.flipkart.com/nothing-phone-3a-black-256-gb/p/itm49557c5a65f9c?pid=MOBH8G3PJJMGUFGH&lid=LSTMOBH8G3PJJMGUFGHFTVDFO&marketplace=FLIPKART&q=nothing+phone+3a&store=tyy%2F4io&srno=s_1_3&otracker=search&otracker1=search&fm=search-autosuggest&iid=c9fcc665-820f-4b09-9940-ac13e342b2c2.MOBH8G3PJJMGUFGH.SEARCH&ppt=sp&ppn=sp&ssid=0imx3j0a0w0000001774523523961&qH=f5c73102c1956fde&ov_redirect=true', inStock: true },
    ],
  },
  {
    name: 'Realme 16 Pro Plus',
    brand: 'Realme', slug: 'realme-16-pro-plus', category: 'phone',
    image: 'https://fdn2.gsmarena.com/vv/pics/realme/realme-16-pro-plus-1.jpg',
    storage: ['128GB', '256GB'], ram: '12GB',
    display: '6.7 inch AMOLED 120Hz Curved',
    camera: '50MP Sony Main + 50MP Periscope Telephoto',
    battery: '5200 mAh', os: 'Android', featured: false,
    scores: { camera: 8, battery: 8, performance: 7, display: 8, value: 9, build: 7, portability: 8 },
    tags: ['photography', 'value', 'budget', 'android'],
    prices: [
      { platform: 'amazon', price: 32999, affiliateUrl: 'https://www.amazon.in/realme-16-Pro-Smartphone-Snapdragon/dp/B0GC5KQSTV/ref=sr_1_3?sr=8-3', inStock: true },
      { platform: 'flipkart', price: 31999, affiliateUrl: 'https://www.flipkart.com/realme-16-pro-5g-master-gold-256-gb/p/itmf8e5c193facd1?pid=MOBHGT68YJGMF89K&lid=LSTMOBHGT68YJGMF89KOENUJH&marketplace=FLIPKART&q=realme+16+pro+plus&store=tyy%2F4io&srno=s_1_1&otracker=search&otracker1=search&fm=organic&iid=d6b5ebc3-e51d-4f98-b1c9-567611616a22.MOBHGT68YJGMF89K.SEARCH&ppt=None&ppn=None&ssid=e9bm0i1xkw0000001774523558480&qH=d0a39726a2a5784e&ov_redirect=true', inStock: true },
    ],
  },
  {
    name: 'Vivo X200 FE',
    brand: 'Vivo',
    slug: 'vivo-x200-fe', category: 'phone',
    image: 'https://m.media-amazon.com/images/I/41AQ2FayWPL._SY300_SX300_QL70_FMwebp_.jpg',
    storage: ['128GB', '256GB'],
    ram: '12GB',
    display: '6.67 inch AMOLED 120Hz',
    camera: '50MP Zeiss Main + 50MP Ultra Wide + 50MP Telephoto',
    battery: '5700 mAh',
     scores: { camera: 8, battery:9, performance: 7, display: 9, value: 8, build: 7, portability: 8 },
    tags: ['photography', 'value', 'budget', 'android'],
    featured: false,
    prices: [
      { platform: 'amazon', price: 49999, affiliateUrl: 'https://www.amazon.in/vivo-X300-Storage-Additional-Exchange/dp/B0G2CB88TC/ref=sr_1_2?sr=8-2', inStock: true },
      { platform: 'flipkart', price: 48999, affiliateUrl: 'https://www.flipkart.com/vivo-x200-5g-natural-green-256-gb/p/itm8a4d46ac97f57?pid=MOBH7443UHDKDZRJ&lid=LSTMOBH7443UHDKDZRJNZWMEP&marketplace=FLIPKART&q=vivo+x200FE&store=tyy%2F4io&srno=s_1_1&otracker=search&otracker1=search&fm=organic&iid=fd51f304-dd1d-41bd-8721-55271692dd01.MOBH7443UHDKDZRJ.SEARCH&ppt=None&ppn=None&ssid=jrbukw3fzk0000001774523593640&qH=c6b9601c4ce71403&ov_redirect=true', inStock: true },
    ],
  },
  {
    name: 'Google Pixel 9a',
    brand: 'Google',
    slug: 'google-pixel-9a', category: 'phone',
    image: 'https://fdn2.gsmarena.com/vv/pics/google/google-pixel-9a-1.jpg',
    storage: ['128GB', '256GB'],
    ram: '8GB',
    display: '6.3 inch OLED 120Hz',
    camera: '48MP Main + 13MP Ultra Wide',
    battery: '5100 mAh',
     scores: { camera: 8, battery: 8, performance: 7, display: 8, value: 9, build: 7, portability: 8 },
    tags: ['photography', 'value', 'budget', 'android'],
    featured: false,
    prices: [
      { platform: 'amazon', price: 49999, affiliateUrl: 'https://www.amazon.in/Google-Pixel-Obsidian-256-RAM/dp/B0F6CY1S9Z/ref=sr_1_1?sr=8-1', inStock: true },
      { platform: 'flipkart', price: 51999, affiliateUrl: 'https://www.flipkart.com/google-pixel-9a-obsidian-256-gb/p/itmf9d1fcfa566cf?pid=MOBH9YMEQUGCHPHN&lid=LSTMOBH9YMEQUGCHPHNSFHZNA&marketplace=FLIPKART&q=google+pixel+9a&store=tyy%2F4io&spotlightTagId=default_BestsellerId_tyy%2F4io&srno=s_1_1&otracker=search&otracker1=search&fm=Search&iid=4558b68f-b50f-4b08-8890-fb6b02f21e7a.MOBH9YMEQUGCHPHN.SEARCH&ppt=sp&ppn=sp&ssid=z5hbcw4tyo0000001774523621268&qH=8545b179236401ba&ov_redirect=true', inStock: true },
    ],
  },
   {
    name: 'Samsung Galaxy A56', brand: 'Samsung', slug: 'samsung-galaxy-a56', category: 'phone',
    image: 'https://m.media-amazon.com/images/I/21h+emgYkKL.jpg', storage: ['128GB', '256GB'], ram: '8GB',
    display: '6.7 inch Super AMOLED 120Hz 1000 nits', camera: '50MP Main + 12MP Ultra Wide + 5MP Macro',
    battery: '5000 mAh 45W', os: 'Android', processor: 'Exynos 1580', weight: '198g',
    features: ['IP67', '5G', '6 years OS updates'],
    featured: false,
    scores: { camera: 7, battery: 8, performance: 7, display: 8, value: 9, build: 8, portability: 8 },
    tags: ['student', 'value', 'android', 'everyday', 'durability'],
    prices: [
      { platform: 'amazon', price: 38999, affiliateUrl: 'https://www.amazon.in/Samsung-Galaxy-Awesome-Gemini-Intelligence/dp/B0DYDQ7PDN/ref=sr_1_2?sr=8-2', inStock: true },
      { platform: 'flipkart', price: 37999, affiliateUrl: 'https://www.flipkart.com/samsung-galaxy-a56', inStock: true },
    ],
  },
  {
    name: 'Xiaomi 17 Ultra', brand: 'Xiaomi', slug: 'xiaomi-17-ultra', category: 'phone',
    image: 'https://m.media-amazon.com/images/I/71E+NLQFhgL._SX425_.jpg', storage: ['256GB', '512GB'], ram: '16GB',
    display: '6.73 inch LTPO AMOLED 120Hz 3200 nits', camera: '50MP Leica 1-inch Main + 50MP Ultra Wide + 200MP Periscope',
    battery: '5410 mAh 90W', os: 'Android', processor: 'Snapdragon 8 Elite', weight: '226g',
    features: ['IP68', 'Ceramic Back', 'Vapor Chamber', 'UFS 4.0'],
    featured: true,
    scores: { camera: 10, battery: 9, performance: 10, display: 10, value: 7, build: 9, portability: 6 },
    tags: ['photography', 'premium', 'android', 'zoom', 'gaming', 'sunlight'],
    prices: [
      { platform: 'amazon', price: 140000, affiliateUrl: 'https://www.amazon.in/XIAOMI-Snapdragon-HyperCharge-Flagship-Experience/dp/B0GMQG7QM5/ref=sr_1_3?sr=8-3', inStock: true },
      { platform: 'flipkart', price: 141000, affiliateUrl: 'https://www.flipkart.com/xiaomi-17-ultra', inStock: false },
    ],
  },
  {
    name: 'iQOO 15 Legend', brand: 'iQOO', slug: 'iqoo-15-legend', category: 'phone',
    image: 'https://m.media-amazon.com/images/I/61OB0B7FA-L._SX425_.jpg', storage: ['128GB', '256GB'], ram: '16GB',
    display: '6.78 inch AMOLED 144Hz 4500 nits', camera: '50MP Main + 50MP Ultra Wide + 64MP Periscope',
    battery: '6100 mAh 120W', os: 'Android', processor: 'Snapdragon 8 Elite', weight: '213g',
    features: ['IP68', 'Vapor Chamber', 'UFS 4.0', 'GT Mode', '5G'],
    featured: false,
    scores: { camera: 8, battery: 10, performance: 10, display: 9, value: 9, build: 8, portability: 8 },
    tags: ['gaming', 'performance', 'battery', 'charging', 'android', 'value'],
    prices: [
      { platform: 'amazon', price: 79999, affiliateUrl: 'https://www.amazon.in/iQOO-Storage-Fastest-Snapdragon-Processor/dp/B0FYGC3YWR/ref=sr_1_3?sr=8-3', inStock: true },
      { platform: 'flipkart', price: 80999, affiliateUrl: 'https://www.flipkart.com/iqoo-15-pro', inStock: true },
    ],
  },
  {
    name: 'Google Pixel 9 Pro', brand: 'Google', slug: 'google-pixel-9-pro', category: 'phone',
    image: 'https://m.media-amazon.com/images/I/51qG7EM6MZL._SX425_.jpg', storage: ['128GB', '256GB', '512GB'], ram: '16GB',
    display: '6.3 inch LTPO OLED 120Hz 3000 nits', camera: '50MP Main + 48MP Ultra Wide + 48MP Telephoto',
    battery: '4700 mAh 45W', os: 'Android', processor: 'Google Tensor G4', weight: '199g',
    features: ['IP68', 'Gorilla Glass Victus 2', '7 years OS updates', 'AI Features'],
    featured: false,
    scores: { camera: 10, battery: 8, performance: 8, display: 9, value: 7, build: 9, portability: 8 },
    tags: ['photography', 'android', 'ai', 'business', 'just-works', 'durability'],
    prices: [
      { platform: 'amazon', price: 85999, affiliateUrl: 'https://www.amazon.in/Google-Pixel-Pro-Obsidian-Storage/dp/B0FLQQF6YP/ref=sr_1_3?sr=8-3', inStock: true },
      { platform: 'flipkart', price: 90999, affiliateUrl: 'https://www.flipkart.com/google-pixel-9-pro', inStock: true },
    ],
  },
  {
    name: 'Vivo X300 Pro', brand: 'Vivo', slug: 'vivo-x300-pro', category: 'phone',
    image: 'https://m.media-amazon.com/images/I/71Gxa9gpbnL._SX425_.jpg', storage: ['256GB', '512GB'], ram: '16GB',
    display: '6.78 inch LTPO AMOLED 120Hz 4500 nits', camera: '50MP Zeiss Main + 50MP Ultra Wide + 200MP Periscope',
    battery: '6000 mAh 90W', os: 'Android', processor: 'Dimensity 9400', weight: '229g',
    features: ['IP69', 'Zeiss Optics', 'Vapor Chamber', '5G'],
    featured: false,
    scores: { camera: 10, battery: 10, performance: 9, display: 10, value: 7, build: 9, portability: 6 },
    tags: ['photography', 'premium', 'battery', 'zoom', 'android', 'sunlight'],
    prices: [
      { platform: 'amazon', price: 94999, affiliateUrl: 'https://www.amazon.in/vivo-X300-Pro-Additional-Exchange/dp/B0G26JXRTX/ref=sr_1_2?sr=8-2', inStock: true },
      { platform: 'flipkart', price: 92999, affiliateUrl: 'https://www.flipkart.com/vivo-x200-pro', inStock: true },
    ],
  },
  {
    name: 'Motorola Edge 60 Pro', brand: 'Motorola', slug: 'motorola-edge-60-pro', category: 'phone',
    image: 'https://m.media-amazon.com/images/I/21eoVbQ8cRL._SX425_.jpg', storage: ['256GB'], ram: '12GB',
    display: '6.67 inch pOLED 144Hz 3000 nits', camera: '50MP Main + 50MP Ultra Wide + 10MP Telephoto',
    battery: '5500 mAh 125W', os: 'Android', processor: 'Dimensity 8350', weight: '185g',
    features: ['IP69', 'Gorilla Glass Victus', 'Vegan Leather', '5G'],
    featured: false,
    scores: { camera: 8, battery: 9, performance: 8, display: 9, value: 9, build: 9, portability: 8 },
    tags: ['value', 'battery', 'android', 'charging', 'durability', 'student'],
    prices: [
      { platform: 'amazon', price: 34999, affiliateUrl: 'https://www.amazon.in/Motorola-Pantone-Shadow-256GB-Storage/dp/B0F83DDCVW/ref=sr_1_1?sr=8-1', inStock: true },
      { platform: 'flipkart', price: 33999, affiliateUrl: 'https://www.flipkart.com/motorola-edge-60-pro-pantone-shadow-256-gb/p/itm3823c3f8f3cc9?pid=MOBH9C9JEHCZYHF2&lid=LSTMOBH9C9JEHCZYHF2XJHF2L&marketplace=FLIPKART&q=motorola+edge+60+pro&store=tyy%2F4io&spotlightTagId=default_BestsellerId_tyy%2F4io&srno=s_1_1&otracker=AS_Query_OrganicAutoSuggest_4_14_na_na_ps&otracker1=AS_Query_OrganicAutoSuggest_4_14_na_na_ps&fm=search-autosuggest&iid=db51b02a-e5ce-4d49-89b8-c08e200ebf5f.MOBH9C9JEHCZYHF2.SEARCH&ppt=sp&ppn=sp&ssid=3pgco3rt0w0000001774695089451&qH=e4b8569b3b50ec7d&ov_redirect=true', inStock: true },
    ],
  },
  {
    name: 'Poco F7 Pro', brand: 'Poco', slug: 'poco-f7-pro', category: 'phone',
    image: 'https://m.media-amazon.com/images/I/41O8KMA8xTL._SX342_.jpg', storage: ['256GB', '512GB'], ram: '12GB',
    display: '6.67 inch AMOLED 144Hz 3200 nits', camera: '50MP Main + 8MP Ultra Wide',
    battery: '6000 mAh 90W', os: 'Android', processor: 'Snapdragon 8 Gen 3', weight: '210g',
    features: ['IP64', 'Vapor Chamber', 'UFS 4.0', '5G'],
    featured: false,
    scores: { camera: 7, battery: 10, performance: 10, display: 8, value: 10, build: 7, portability: 7 },
    tags: ['gaming', 'performance', 'battery', 'value', 'budget', 'android'],
    prices: [
      { platform: 'amazon', price: 29999, affiliateUrl: 'https://www.amazon.in/POCO-Snapdragon-Processor-Battery-Display/dp/B0G52W6CFB/ref=sr_1_3?sr=8-3', inStock: true },
      { platform: 'flipkart', price: 28999, affiliateUrl: 'https://www.flipkart.com/poco-f7-pro', inStock: true },
    ],
  },
  {
    name: 'Oppo Find X9 Pro', brand: 'Oppo', slug: 'oppo-find-x9-pro', category: 'phone',
    image: 'https://m.media-amazon.com/images/I/71NqN92-ilL._SX425_.jpg', storage: ['512GB'], ram: '16GB',
    display: '6.78 inch LTPO AMOLED 120Hz 4500 nits', camera: '50MP Hasselblad Main + 50MP Ultra Wide + 50MP Periscope',
    battery: '5910 mAh 80W', os: 'Android', processor: 'Dimensity 9400', weight: '215g',
    features: ['IP69', 'Hasselblad Tuning', 'Vapor Chamber', '5G'],
    featured: false,
    scores: { camera: 9, battery: 9, performance: 9, display: 10, value: 8, build: 9, portability: 8 },
    tags: ['photography', 'premium', 'android', 'zoom', 'battery', 'sunlight'],
    prices: [
      { platform: 'amazon', price: 89999, affiliateUrl: 'https://www.amazon.in/Titanium-Charcoal-Storage-Additional-Exchange/dp/B0FXXJRXVX/ref=sr_1_1?sr=8-1', inStock: true },
      { platform: 'flipkart', price: 87999, affiliateUrl: 'https://www.flipkart.com/oppo-find-x8-pro', inStock: true },
    ],
  },
  {
    name: 'Redmi Note 14 Pro Plus', brand: 'Xiaomi', slug: 'redmi-note-14-pro-plus', category: 'phone',
    image: 'https://www.amazon.in/Xiaomi-Note-14-Pro-5G/dp/B0DQLTWBH7/ref=sr_1_3?sr=8-3', storage: ['128GB', '256GB'], ram: '8GB',
    display: '6.67 inch AMOLED 120Hz 3000 nits', camera: '200MP Main + 8MP Ultra Wide + 2MP Macro',
    battery: '6200 mAh 90W', os: 'Android', processor: 'Dimensity 1400 Ultra', weight: '204g',
    features: ['IP68', '5G'],
    featured: false,
    scores: { camera: 8, battery: 10, performance: 7, display: 8, value: 10, build: 7, portability: 8 },
    tags: ['budget', 'battery', 'student', 'value', 'android', 'photography'],
    prices: [
      { platform: 'amazon', price: 27999, affiliateUrl: 'https://www.amazon.in/Xiaomi-Note-14-Pro-5G/dp/B0DQLTWBH7/ref=sr_1_3?sr=8-3', inStock: true },
      { platform: 'flipkart', price: 26999, affiliateUrl: 'https://www.flipkart.com/redmi-note-14-pro-plus', inStock: true },
    ],
  },
  {
    name: 'Samsung Galaxy F55', brand: 'Samsung', slug: 'samsung-galaxy-f55', category: 'phone',
    image: 'https://m.media-amazon.com/images/I/51qj8Dm2p3L._SX425_.jpg', storage: ['128GB', '256GB'], ram: '8GB',
    display: '6.7 inch Super AMOLED 120Hz', camera: '50MP Main + 8MP Ultra Wide + 2MP Macro',
    battery: '5000 mAh 45W', os: 'Android', processor: 'Snapdragon 7 Gen 1', weight: '190g',
    features: ['IP67', '5G'],
    featured: false,
    scores: { camera: 7, battery: 8, performance: 7, display: 8, value: 9, build: 7, portability: 8 },
    tags: ['student', 'everyday', 'value', 'android', 'budget'],
    prices: [
      { platform: 'amazon', price: 26999, affiliateUrl: 'https://www.amazon.in/SAMSUNG-Galaxy-F56-Green-128/dp/B0FY2K8D9S/ref=sr_1_5?sr=8-5', inStock: true },
      { platform: 'flipkart', price: 25999, affiliateUrl: 'https://www.flipkart.com/samsung-galaxy-f55', inStock: true },
    ],
  },
  {
    name: 'Tecno Phantom X2 Pro', brand: 'Tecno', slug: 'tecno-phantom-x2-pro', category: 'phone',
    image: '/phones/tecno-phantom-x2-pro.jpg', storage: ['256GB'], ram: '12GB',
    display: '6.8 inch AMOLED 120Hz', camera: '50MP Periscope Main + 50MP Ultra Wide',
    battery: '5160 mAh 45W', os: 'Android', processor: 'Dimensity 9000', weight: '200g',
    features: ['5G'],
    featured: false,
    scores: { camera: 8, battery: 7, performance: 8, display: 8, value: 9, build: 7, portability: 8 },
    tags: ['value', 'photography', 'android', 'zoom'],
    prices: [
      { platform: 'amazon', price: 34999, affiliateUrl: 'https://www.amazon.in/dp/tecno-phantom-x2-pro', inStock: true },
      { platform: 'flipkart', price: 33999, affiliateUrl: 'https://www.flipkart.com/tecno-phantom-x2-pro', inStock: true },
    ],
  },


  // ─── LAPTOPS ──────────────────────────────────────────────
  {
    name: 'MacBook Air M4',
    brand: 'Apple', slug: 'apple-macbook-air-m4', category: 'laptop',
    image: 'https://m.media-amazon.com/images/I/71pKJ+Mjd8L._SX679_.jpg',
    storage: ['256GB SSD', '512GB SSD', '1TB SSD'], ram: '16GB',
    display: '13.6 inch Liquid Retina',
    processor: 'Apple M4', os: 'macOS',
    weight: '1.24 kg', battery: '18 hours', featured: true,
    scores: { camera: 6, battery: 10, performance: 9, display: 9, value: 7, build: 10, portability: 10 },
    tags: ['student', 'business', 'creative', 'programming', 'premium', 'lightweight'],
    prices: [
      { platform: 'amazon', price: 99999, affiliateUrl: 'https://www.amazon.in/Apple-MacBook-13-inch-10-core-Unified/dp/B0DZDDKTQZ/ref=sr_1_1_sspa?sr=8-1-spons&aref=TKZsjhflX8&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY', inStock: true },
      { platform: 'flipkart', price: 101999, affiliateUrl: 'https://www.flipkart.com/macbook-air-m4', inStock: true },
    ],
  },
  {
    name: 'MacBook Pro M4',
    brand: 'Apple', slug: 'apple-macbook-pro-m4', category: 'laptop',
    image: 'https://m.media-amazon.com/images/I/61S+iQmF5NL._SX679_.jpg',
    storage: ['512GB SSD', '1TB SSD', '2TB SSD'], ram: '24GB',
    display: '14.2 inch Liquid Retina XDR ProMotion',
    processor: 'Apple M4 Pro', os: 'macOS',
    weight: '1.61 kg', battery: '24 hours', featured: true,
    scores: { camera: 7, battery: 10, performance: 10, display: 10, value: 6, build: 10, portability: 9 },
    tags: ['creative', 'programming', 'business', 'premium', 'video-editing'],
    prices: [
      { platform: 'amazon', price: 189999, affiliateUrl: 'https://www.amazon.in/Apple-2024-MacBook-Laptop-10%E2%80%91core/dp/B0DLHN2KNG/ref=sr_1_1_sspa?sr=8-1-spons&aref=dODEwj3s9V&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1', inStock: true },
      { platform: 'flipkart', price: 191999, affiliateUrl: 'https://www.flipkart.com/macbook-pro-m4', inStock: true },
    ],
  },
  {
    name: 'ASUS ROG Zephyrus G14',
    brand: 'ASUS', slug: 'asus-rog-zephyrus-g14', category: 'laptop',
    image: 'https://m.media-amazon.com/images/I/41j-MLo-hnL._SY300_SX300_QL70_FMwebp_.jpg',
    storage: ['512GB SSD', '1TB SSD'], ram: '16GB',
    display: '14 inch QHD+ OLED 165Hz',
    processor: 'AMD Ryzen 9 + RTX 4060', os: 'Windows',
    weight: '1.65 kg', battery: '10 hours', featured: true,
    scores: { camera: 5, battery: 7, performance: 10, display: 10, value: 8, build: 9, portability: 8 },
    tags: ['gaming', 'creative', 'video-editing', 'performance', 'student'],
    prices: [
      { platform: 'amazon', price: 129999, affiliateUrl: 'https://www.amazon.in/ASUS-Zephyrus-5060-8GB-Windows-GA403UM-QS007WS/dp/B0F9X945VW/ref=sr_1_3?sr=8-3', inStock: true },
      { platform: 'flipkart', price: 127999, affiliateUrl: 'https://www.flipkart.com/asus-rog-zephyrus-g14', inStock: true },
    ],
  },
  {
    name: 'Dell XPS 13',
    brand: 'Dell', slug: 'dell-xps-13', category: 'laptop',
    image: 'https://m.media-amazon.com/images/I/712CAwRf6xL._SX679_.jpg',
    storage: ['512GB SSD', '1TB SSD'], ram: '16GB',
    display: '13.4 inch FHD+ OLED',
    processor: 'Intel Core Ultra 7', os: 'Windows',
    weight: '1.17 kg', battery: '12 hours', featured: false,
    scores: { camera: 6, battery: 8, performance: 8, display: 9, value: 7, build: 9, portability: 10 },
    tags: ['business', 'student', 'lightweight', 'programming', 'premium'],
    prices: [
      { platform: 'amazon', price: 119999, affiliateUrl: 'https://www.amazon.in/Dell-XPS-13-9345-Snapdragon/dp/B0DJM69JDV/ref=sr_1_3?sr=8-3', inStock: true },
      { platform: 'flipkart', price: 117999, affiliateUrl: 'https://www.flipkart.com/dell-xps-13', inStock: true },
    ],
  },
  {
    name: 'Lenovo IdeaPad Slim 5',
    brand: 'Lenovo', slug: 'lenovo-ideapad-slim-5', category: 'laptop',
    image: 'https://m.media-amazon.com/images/I/616BhYEGRHL._SX679_.jpg',
    storage: ['512GB SSD'], ram: '16GB',
    display: '15.6 inch FHD IPS',
    processor: 'AMD Ryzen 7 7730U', os: 'Windows',
    weight: '1.67 kg', battery: '10 hours', featured: false,
    scores: { camera: 5, battery: 7, performance: 7, display: 7, value: 10, build: 7, portability: 8 },
    tags: ['student', 'budget', 'value', 'programming', 'everyday'],
    prices: [
      { platform: 'amazon', price: 54999, affiliateUrl: 'https://www.amazon.in/Lenovo-IdeaPad-Integrated-Graphics-83J2000HIN/dp/B0DVGF96B4/ref=sr_1_3?sr=8-3', inStock: true },
      { platform: 'flipkart', price: 52999, affiliateUrl: 'https://www.flipkart.com/lenovo-ideapad-slim-5', inStock: true },
    ],
  },
  {
    name: 'HP Pavilion Plus 14',
    brand: 'HP', slug: 'hp-pavilion-plus-14', category: 'laptop',
    image: 'https://m.media-amazon.com/images/I/71KR4mF8JLL._SX679_.jpg',
    storage: ['512GB SSD'], ram: '16GB',
    display: '14 inch 2.8K OLED 120Hz',
    processor: 'Intel Core i7-13700H', os: 'Windows',
    weight: '1.46 kg', battery: '11 hours', featured: false,
    scores: { camera: 5, battery: 7, performance: 8, display: 9, value: 9, build: 8, portability: 9 },
    tags: ['student', 'value', 'creative', 'everyday', 'budget'],
    prices: [
      { platform: 'amazon', price: 79999, affiliateUrl: 'https://www.amazon.in/HP-Pavilion-i5-1335U-14-inch-ew0116TU/dp/B0CWDBJ3Q8/ref=sr_1_4?sr=8-4', inStock: true },
      { platform: 'flipkart', price: 77999, affiliateUrl: 'https://www.flipkart.com/hp-pavilion-plus-14', inStock: true },
    ],
  },
 {
    name: 'ASUS Vivobook 16X OLED', brand: 'ASUS', slug: 'asus-vivobook-16x-oled', category: 'laptop',
    image: '/laptops/asus-vivobook-16x.jpg', storage: ['512GB SSD', '1TB SSD'], ram: '16GB',
    display: '16 inch 3.2K OLED 120Hz', processor: 'AMD Ryzen 7 7745HX', os: 'Windows',
    weight: '1.88 kg', battery: '10 hours', features: ['Harman Kardon Audio', 'ASUS DialPad'],
    featured: false,
    scores: { camera: 5, battery: 7, performance: 8, display: 10, value: 9, build: 8, portability: 7 },
    tags: ['creative', 'student', 'video-editing', 'value', 'everyday'],
    prices: [
      { platform: 'amazon', price: 74999, affiliateUrl: 'https://www.amazon.in/dp/asus-vivobook-16x', inStock: true },
      { platform: 'flipkart', price: 72999, affiliateUrl: 'https://www.flipkart.com/asus-vivobook-16x-oled', inStock: true },
    ],
  },
  {
    name: 'Lenovo ThinkPad X1 Carbon', brand: 'Lenovo', slug: 'lenovo-thinkpad-x1-carbon', category: 'laptop',
    image: '/laptops/lenovo-thinkpad-x1.jpg', storage: ['512GB SSD', '1TB SSD'], ram: '16GB',
    display: '14 inch 2.8K IPS Anti-glare', processor: 'Intel Core Ultra 7 165U', os: 'Windows',
    weight: '1.12 kg', battery: '15 hours', features: ['Military Grade MIL-SPEC', 'Thunderbolt 4', 'TrackPoint'],
    featured: false,
    scores: { camera: 6, battery: 9, performance: 8, display: 8, value: 6, build: 10, portability: 10 },
    tags: ['business', 'premium', 'lightweight', 'programming', 'durability'],
    prices: [
      { platform: 'amazon', price: 149999, affiliateUrl: 'https://www.amazon.in/dp/thinkpad-x1-carbon', inStock: true },
      { platform: 'flipkart', price: 147999, affiliateUrl: 'https://www.flipkart.com/lenovo-thinkpad-x1-carbon', inStock: true },
    ],
  },
  {
    name: 'Acer Nitro V 15', brand: 'Acer', slug: 'acer-nitro-v-15', category: 'laptop',
    image: '/laptops/acer-nitro-v15.jpg', storage: ['512GB SSD'], ram: '16GB',
    display: '15.6 inch FHD IPS 144Hz', processor: 'Intel Core i5-13420H + RTX 4050', os: 'Windows',
    weight: '2.2 kg', battery: '8 hours', features: ['Dual Fan Cooling', 'DTS:X Ultra Audio'],
    featured: false,
    scores: { camera: 4, battery: 6, performance: 9, display: 7, value: 10, build: 7, portability: 6 },
    tags: ['gaming', 'budget', 'student', 'value', 'performance'],
    prices: [
      { platform: 'amazon', price: 64999, affiliateUrl: 'https://www.amazon.in/dp/acer-nitro-v15', inStock: true },
      { platform: 'flipkart', price: 62999, affiliateUrl: 'https://www.flipkart.com/acer-nitro-v-15', inStock: true },
    ],
  },
  {
    name: 'MSI Stealth 16 AI', brand: 'MSI', slug: 'msi-stealth-16-ai', category: 'laptop',
    image: '/laptops/msi-stealth-16.jpg', storage: ['1TB SSD', '2TB SSD'], ram: '32GB',
    display: '16 inch QHD+ OLED 240Hz', processor: 'Intel Core Ultra 9 + RTX 4070', os: 'Windows',
    weight: '1.99 kg', battery: '10 hours', features: ['Thunderbolt 5', 'Per-Key RGB', 'Vapor Chamber'],
    featured: false,
    scores: { camera: 5, battery: 7, performance: 10, display: 10, value: 7, build: 9, portability: 7 },
    tags: ['gaming', 'creative', 'premium', 'video-editing', 'performance'],
    prices: [
      { platform: 'amazon', price: 189999, affiliateUrl: 'https://www.amazon.in/dp/msi-stealth-16', inStock: true },
      { platform: 'flipkart', price: 187999, affiliateUrl: 'https://www.flipkart.com/msi-stealth-16-ai', inStock: true },
    ],
  },
  {
    name: 'HP Spectre x360 14', brand: 'HP', slug: 'hp-spectre-x360-14', category: 'laptop',
    image: '/laptops/hp-spectre-x360.jpg', storage: ['1TB SSD'], ram: '16GB',
    display: '14 inch 2.8K OLED Touch 120Hz', processor: 'Intel Core Ultra 7 155H', os: 'Windows',
    weight: '1.58 kg', battery: '17 hours', features: ['360° Hinge', 'Active Pen', 'Thunderbolt 4', 'Privacy Camera'],
    featured: false,
    scores: { camera: 7, battery: 9, performance: 8, display: 10, value: 7, build: 10, portability: 9 },
    tags: ['business', 'premium', 'creative', 'lightweight', '2-in-1'],
    prices: [
      { platform: 'amazon', price: 159999, affiliateUrl: 'https://www.amazon.in/dp/hp-spectre-x360', inStock: true },
      { platform: 'flipkart', price: 157999, affiliateUrl: 'https://www.flipkart.com/hp-spectre-x360-14', inStock: true },
    ],
  },
];


const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('MongoDB connected ✅');
    await Product.deleteMany({});
    console.log('Cleared old products 🗑️');
    await Product.insertMany(products);
    console.log(`Seeded ${products.length} products ✅`);
    console.log(`  📱 Phones: ${products.filter(p => p.category === 'phone').length}`);
    console.log(`  💻 Laptops: ${products.filter(p => p.category === 'laptop').length}`);
    process.exit(0);
  } catch (err) {
    console.error('Seed error:', err.message);
    process.exit(1);
  }
};

seedDB();